# Generated by Django 4.2 on 2023-10-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_contact', models.CharField(max_length=200)),
                ('client_billing_address', models.CharField(max_length=255)),
                ('purchased_products', models.TextField()),
                ('order_date', models.DateField()),
                ('order_amount', models.FloatField()),
                ('commissioned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.commissionedemployee')),
            ],
        ),
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.employee')),
            ],
            options={
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
