# Generated by Django 4.2 on 2023-10-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('hour_or_month', models.BooleanField()),
                ('hourly_rate', models.FloatField(blank=True, null=True)),
                ('monthly_salary', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('mailed', 'mailed')], max_length=20)),
                ('payment_address', models.CharField(blank=True, max_length=200)),
                ('payment_cardID', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('hour_limit', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionedEmployee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userApp.employee')),
                ('commission_rate', models.FloatField()),
            ],
            bases=('userApp.employee',),
        ),
    ]
